### ISSUE TITLE
Recommended Install On Cf Workers?

### ISSUE THREAD

**Issue by jiriteach** [amodm/ip-lookup#2]
Hi - I have published this as part of workers and the base IP is working but lookups dont return any additional info. How do I ensure these are properly installed?

Thanks

**Comment by amodm** [comment]
That's because when making a request, the worker receives only the IP information in the request. Cloudflare uses an IP-Country geomap to give you at least the country. Beyond that, any info is fetched from a pre-populated [Cloudflare KV](https://www.cloudflare.com/en-gb/products/workers-kv/).

If you plan to use this code to run your own independent services which provides full network lookup, you'll need to have a KV bucket installed under the alias IP2NETWORK, and upload all the [data](https://github.com/amodm/ip-lookup/blob/master/data/README.md) to that.

You can find one of the uses of this KV, as well as the format of the KV keys, [here](https://github.com/amodm/ip-lookup/blob/2aff2a5c9c06b453ea6300db377c79e4a7333885/index.js#L77).

I'm closing this issue, but you may re-open it if my interpretation of your statements is incorrect.

**Comment by jiriteach** [comment]
Thanks for the clarification @amodm.
